//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prielbrusye
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skiresortEntities : DbContext
    {
        private static skiresortEntities _context = new skiresortEntities();
        public skiresortEntities()
            : base("name=skiresortEntities")
        {
        }
        public static skiresortEntities GetContext()
        {
            if (_context == null)
                _context = new skiresortEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<login_history> login_history { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
