//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prielbrusye
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_history
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
    }
}
