//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prielbrusye
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string order_code { get; set; }
        public string date_start { get; set; }
        public string time { get; set; }
        public int id_client { get; set; }
        public string services { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public int time_rental { get; set; }
    
        public virtual client client { get; set; }
        public virtual status status1 { get; set; }
    }
}
